apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: dockkubeacr.azurecr.io/webapi:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"   # Request 250 millicores (0.25 CPU)
            memory: "512Mi"  # Request 512MB of memory
          limits:
            cpu: "500m"   # Limit CPU usage to 500 millicores (0.5 CPU)
            memory: "1Gi"   # Limit memory usage to 1GB
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
